node_types:
  dice.components.mock.WebServer:
    derived_from: cloudify.nodes.WebServer
    interfaces:
      cloudify.interfaces.lifecycle:
        configure: dice.dice_plugin.tasks.test.configure
        delete: dice.dice_plugin.tasks.test.delete
        start: dice.dice_plugin.tasks.test.start
        stop: dice.dice_plugin.tasks.test.stop
    properties:
      description:
        default: This is an example page.
        description: This will appear as the body of the page
      port:
        default: 8080
      title:
        default: Cloudify Hello World
        description: This will appear as the title of the page
  dice.firewall_rules.Base:
    derived_from: dice.firewall_rules.Unimplemented
  dice.firewall_rules.Unimplemented:
    derived_from: cloudify.nodes.Root
  dice.firewall_rules.mock.WebServer:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 8080
          remote_ip_prefix: 0.0.0.0/0
        - port: 22
          remote_ip_prefix: 0.0.0.0/0
  dice.hosts.Custom:
    derived_from: cloudify.flexiant.nodes.Server
    properties:
      agent_key:
        default:
          get_input: agent_key
      auth:
        default:
          customer:
            get_input: customer
          password:
            get_input: password
          url:
            get_input: service_url
          username:
            get_input: username
          verify_ca_cert: false
      cloudify_agent:
        default:
          user:
            get_input: agent_user
      network:
        default:
          get_input: network
      vdc:
        default:
          get_input: vdc
  dice.hosts.Large:
    derived_from: dice.hosts.Custom
    properties:
      disk:
        default:
          get_input: large_disk
      image:
        default:
          get_input: large_image_id
      server_type:
        default:
          get_input: large_server_type
  dice.hosts.Medium:
    derived_from: dice.hosts.Custom
    properties:
      disk:
        default:
          get_input: medium_disk
      image:
        default:
          get_input: medium_image_id
      server_type:
        default:
          get_input: medium_server_type
  dice.hosts.Small:
    derived_from: dice.hosts.Custom
    properties:
      disk:
        default:
          get_input: small_disk
      image:
        default:
          get_input: small_image_id
      server_type:
        default:
          get_input: small_server_type
  dice.hosts.Unimplemented:
    derived_from: cloudify.nodes.Root
plugins:
  dice:
    executor: host_agent
    source: https://github.com/dice-project/DICE-Deployment-Cloudify/archive/develop.zip
relationships:
  dice.relationships.ContainedIn:
    derived_from: cloudify.relationships.contained_in
  dice.relationships.ProtectedBy:
    derived_from: dice.relationships.Unimplemented
  dice.relationships.Unimplemented:
    derived_from: cloudify.relationships.depends_on
