# DICE Deployment Service

node_types:

  dice.components.DeploymentService:
    derived_from: dice.chef.SoftwareComponent
    properties:
      sources:
        description: Application sources for deployment service
        default: { get_input: sources }
      manager:
        description: Cloudify Manager instance we wrap
        default: { get_input: cfy_manager}
      manager_user:
        description: Cloudify Manager instance username
        default: { get_input: cfy_manager_username }
      manager_pass:
        description: Cloudify Manager instance password
        default: { get_input: cfy_manager_password }
      superuser_username:
        description: Username part of the superuser credentials to create
        default: { get_input: superuser_username }
      superuser_password:
        description: Password part of the superuser credentials to create
        default: { get_input: superuser_password }
      superuser_email:
        description: E-mail address to assign to the superuser
        default: { get_input: superuser_email }
      debug_mode:
        description: Enable debug mode
        default: { get_input: enable_debug }
      ssh_key:
        description: Extra SSH public key
        default: { get_input: ssh_key }

      configure_runlist:
        default:
          - recipe[apt::default]
          - recipe[dice-common::host]
          - recipe[dice-deployment-service::default]
          - recipe[dice-common::consul-common]
          - recipe[dice-common::consul-server]


  dice.firewall_rules.DeploymentService:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
          - remote_ip_prefix: 0.0.0.0/0
            port: 22
          - remote_ip_prefix: 0.0.0.0/0
            port: 53
          - remote_ip_prefix: 0.0.0.0/0
            port: 53
            protocol: udp
          - remote_ip_prefix: 0.0.0.0/0
            port: 80
          - remote_ip_prefix: 0.0.0.0/0
            port: 5555
          - remote_ip_prefix: 0.0.0.0/0
            port_range_min: 8300
            port_range_max: 8302
          - remote_ip_prefix: 0.0.0.0/0
            port_range_min: 8300
            port_range_max: 8302
            protocol: udp
          - remote_ip_prefix: 0.0.0.0/0
            port: 15672
