node_types:
  dice.LogicalNode:
    derived_from: cloudify.nodes.Root
    interfaces:
      dice.interfaces.reconfiguration:
        reset: {}
        update_configuration:
          implementation: dice.dice_plugin.tasks.base.update_configuration
          inputs:
            configuration:
              default: {}
    properties:
      configuration:
        default: {}
        description: 'This propery holds arbitrary configuration data that can be
          used by installation procedure.

          '
  dice.SoftwareComponent:
    derived_from: cloudify.nodes.SoftwareComponent
    interfaces:
      dice.interfaces.reconfiguration:
        reset: {}
        update_configuration:
          implementation: dice.dice_plugin.tasks.base.update_configuration
          inputs:
            configuration:
              default: {}
    properties:
      configuration:
        default: {}
        description: 'This propery holds arbitrary configuration data that can be
          used by installation procedure.

          '
  dice.chef.SoftwareComponent:
    derived_from: cloudify.chef.nodes.SoftwareComponent
    interfaces:
      dice.interfaces.reconfiguration:
        reset: {}
        update_configuration:
          implementation: dice.dice_plugin.tasks.base.update_configuration
          inputs:
            configuration:
              default: {}
    properties:
      chef_attributes:
        default: {}
        description: 'Chef attributes that are supplied to all runlists

          '
      chef_config:
        default:
          attributes:
            get_property:
            - SELF
            - chef_attributes
          chef_repo: https://github.com/dice-project/DICE-Chef-Repository/archive/0.1.5.tar.gz
          runlists:
            configure:
              get_property:
              - SELF
              - configure_runlist
            create:
              get_property:
              - SELF
              - create_runlist
            delete:
              get_property:
              - SELF
              - delete_runlist
            start:
              get_property:
              - SELF
              - start_runlist
            stop:
              get_property:
              - SELF
              - stop_runlist
          version: 12.11.18
      configuration:
        default: {}
        description: 'This propery holds arbitrary configuration data that can be
          used by installation procedure.

          '
      configure_runlist:
        default: null
        description: 'Runlist that is executed when configuring node (this is where
          all that /etc/ files should be installed).

          '
      create_runlist:
        default: null
        description: 'Runlist that is executed when creating node instance (this is
          where file installation should take place).

          '
      delete_runlist:
        default: null
        description: 'Runlist that deletes the node (should delete ALL installed files,
          including but not limited to configuration files, files that are produced
          while running, ...).

          '
      start_runlist:
        default: null
        description: 'Runlist that starts the node (this is where relevant services
          should be enabled and started).

          '
      stop_runlist:
        default: null
        description: 'Runlist that stops the node (most likely, services will be stopped
          and disabled here).

          '
  dice.components.DeploymentService:
    derived_from: dice.chef.SoftwareComponent
    properties:
      configure_runlist:
        default:
        - recipe[apt::default]
        - recipe[dice-common::host]
        - recipe[dice-deployment-service::default]
        - recipe[dice-common::consul-common]
        - recipe[dice-common::consul-server]
      debug_mode:
        default:
          get_input: enable_debug
        description: Enable debug mode
      manager:
        default:
          get_input: cfy_manager
        description: Cloudify Manager instance we wrap
      manager_pass:
        default:
          get_input: cfy_manager_password
        description: Cloudify Manager instance password
      manager_user:
        default:
          get_input: cfy_manager_username
        description: Cloudify Manager instance username
      sources:
        default:
          get_input: sources
        description: Application sources for deployment service
      ssh_key:
        default:
          get_input: ssh_key
        description: Extra SSH public key
      superuser_email:
        default:
          get_input: superuser_email
        description: E-mail address to assign to the superuser
      superuser_password:
        default:
          get_input: superuser_password
        description: Password part of the superuser credentials to create
      superuser_username:
        default:
          get_input: superuser_username
        description: Username part of the superuser credentials to create
  dice.components.cassandra.Base:
    derived_from: dice.chef.SoftwareComponent
    properties:
      chef_attributes:
        default:
          java:
            jdk_version: '8'
      configure_runlist:
        default:
        - recipe[java::default]
        - recipe[cassandra::default]
        - recipe[cassandra::configure]
      start_runlist:
        default:
        - recipe[cassandra::start]
  dice.components.cassandra.Seed:
    derived_from: dice.components.cassandra.Base
  dice.components.cassandra.Worker:
    derived_from: dice.components.cassandra.Base
  dice.components.hadoop.Base:
    derived_from: dice.chef.SoftwareComponent
    properties:
      create_runlist:
        default:
        - recipe[hosts::default]
        - recipe[apt::default]
        - recipe[java::default]
        - recipe[hadoop-upstream::default]
  dice.components.hadoop.DataNode:
    derived_from: dice.components.hadoop.Base
    properties:
      configure_runlist:
        default:
        - recipe[hadoop-upstream::hdfs-configure]
        - recipe[hadoop-upstream::datanode-configure]
      start_runlist:
        default:
        - recipe[hadoop-upstream::datanode-start]
  dice.components.hadoop.NameNode:
    derived_from: dice.components.hadoop.Base
    properties:
      configure_runlist:
        default:
        - recipe[hadoop-upstream::hdfs-configure]
        - recipe[hadoop-upstream::namenode-configure]
      start_runlist:
        default:
        - recipe[hadoop-upstream::namenode-start]
  dice.components.hadoop.NodeManager:
    derived_from: dice.components.hadoop.Base
    properties:
      configure_runlist:
        default:
        - recipe[hadoop-upstream::yarn-configure]
        - recipe[hadoop-upstream::nodemanager-configure]
      start_runlist:
        default:
        - recipe[hadoop-upstream::nodemanager-start]
  dice.components.hadoop.ResourceManager:
    derived_from: dice.components.hadoop.Base
    properties:
      configure_runlist:
        default:
        - recipe[hadoop-upstream::yarn-configure]
      start_runlist:
        default:
        - recipe[hadoop-upstream::resourcemanager-start]
  dice.components.mock.WebServer:
    derived_from: cloudify.nodes.WebServer
    interfaces:
      cloudify.interfaces.lifecycle:
        configure: dice.dice_plugin.tasks.test.configure
        delete: dice.dice_plugin.tasks.test.delete
        start: dice.dice_plugin.tasks.test.start
        stop: dice.dice_plugin.tasks.test.stop
    properties:
      description:
        default: This is an example page.
        description: This will appear as the body of the page
      port:
        default: 8080
      title:
        default: Cloudify Hello World
        description: This will appear as the title of the page
  dice.components.spark.Base:
    derived_from: dice.chef.SoftwareComponent
    properties:
      configure_runlist:
        default:
        - recipe[spark::configure]
      create_runlist:
        default:
        - recipe[dice-common::host]
        - recipe[apt::default]
        - recipe[java::default]
        - recipe[spark::default]
      start_runlist:
        default:
        - recipe[spark::start]
  dice.components.spark.Master:
    derived_from: dice.components.spark.Base
    properties:
      chef_attributes:
        default:
          spark:
            type: master
  dice.components.spark.Worker:
    derived_from: dice.components.spark.Base
    properties:
      chef_attributes:
        default:
          spark:
            type: worker
  dice.components.storm.Nimbus:
    derived_from: dice.chef.SoftwareComponent
    properties:
      configure_runlist:
        default:
        - recipe[apt::default@2.9.2]
        - recipe[java::default@1.36.0]
        - recipe[storm-cluster::common@0.0.25]
        - recipe[storm-cluster::configure@0.0.25]
      start_runlist:
        default:
        - recipe[storm-cluster::start_nimbus@0.0.25]
        - recipe[storm-cluster::start_supervisor@0.0.25]
  dice.components.storm.Topology:
    derived_from: dice.LogicalNode
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: dice.dice_plugin.tasks.storm.submit_topology
          inputs:
            jar:
              default:
                get_property:
                - SELF
                - application
            klass:
              default:
                get_property:
                - SELF
                - topology_class
            name:
              default:
                get_property:
                - SELF
                - topology_name
        stop:
          implementation: dice.dice_plugin.tasks.storm.kill_topology
          inputs:
            name:
              default:
                get_property:
                - SELF
                - topology_name
    properties:
      application:
        description: 'Location of topology jar file. If this is relative path, file
          is assumed to be part of the blueprint package. If this URL, file will be
          downloaded.

          '
      topology_class:
        description: 'Class name that contains Storm topology

          '
      topology_name:
        description: 'Topology name (this name will be seen in Storm UI)

          '
  dice.components.storm.Worker:
    derived_from: dice.chef.SoftwareComponent
    properties:
      configure_runlist:
        default:
        - recipe[apt::default@2.9.2]
        - recipe[java::default@1.36.0]
        - recipe[storm-cluster::common@0.0.25]
        - recipe[storm-cluster::configure@0.0.25]
      start_runlist:
        default:
        - recipe[storm-cluster::start_supervisor@0.0.25]
  dice.components.zookeeper.Quorum:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          executor: central_deployment_agent
          implementation: dice.dice_plugin.tasks.zookeeper.merge_config
  dice.components.zookeeper.Server:
    derived_from: dice.chef.SoftwareComponent
    properties:
      configure_runlist:
        default:
        - recipe[apt::default@2.9.2]
        - recipe[java::default@1.36.0]
        - recipe[hadoop::default@2.0.10]
        - recipe[hadoop::zookeeper_server@2.0.10]
        - recipe[hadoop::zookeeper_configure@2.0.10]
      start_runlist:
        default:
        - recipe[hadoop::zookeeper_start@2.0.10]
  dice.firewall_rules.Base:
    derived_from: dice.firewall_rules.Unimplemented
  dice.firewall_rules.DeploymentService:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 22
          remote_ip_prefix: 0.0.0.0/0
        - port: 53
          remote_ip_prefix: 0.0.0.0/0
        - port: 53
          protocol: udp
          remote_ip_prefix: 0.0.0.0/0
        - port: 80
          remote_ip_prefix: 0.0.0.0/0
        - port: 5555
          remote_ip_prefix: 0.0.0.0/0
        - port_range_max: 8302
          port_range_min: 8300
          remote_ip_prefix: 0.0.0.0/0
        - port_range_max: 8302
          port_range_min: 8300
          protocol: udp
          remote_ip_prefix: 0.0.0.0/0
        - port: 15672
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.Unimplemented:
    derived_from: cloudify.nodes.Root
  dice.firewall_rules.cassandra.Common:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 7000
          remote_ip_prefix: 0.0.0.0/0
        - port: 7001
          remote_ip_prefix: 0.0.0.0/0
        - port: 7199
          remote_ip_prefix: 0.0.0.0/0
        - port: 9042
          remote_ip_prefix: 0.0.0.0/0
        - port: 9160
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.hadoop.DataNode:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 50010
          remote_ip_prefix: 0.0.0.0/0
        - port: 50020
          remote_ip_prefix: 0.0.0.0/0
        - port: 50075
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.hadoop.NameNode:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 8020
          remote_ip_prefix: 0.0.0.0/0
        - port: 50070
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.hadoop.NodeManager:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 8040
          remote_ip_prefix: 0.0.0.0/0
        - port: 8042
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.hadoop.ResourceManager:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 8030
          remote_ip_prefix: 0.0.0.0/0
        - port: 8031
          remote_ip_prefix: 0.0.0.0/0
        - port: 8032
          remote_ip_prefix: 0.0.0.0/0
        - port: 8033
          remote_ip_prefix: 0.0.0.0/0
        - port: 8088
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.mock.WebServer:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 8080
          remote_ip_prefix: 0.0.0.0/0
        - port: 22
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.spark.Master:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 6066
          remote_ip_prefix: 0.0.0.0/0
        - port: 7077
          remote_ip_prefix: 0.0.0.0/0
  dice.firewall_rules.spark.Worker:
    derived_from: dice.firewall_rules.Base
    properties:
      rules:
        default:
        - port: 7078
          remote_ip_prefix: 0.0.0.0/0
  dice.hosts.Custom:
    derived_from: cloudify.flexiant.nodes.Server
    properties:
      agent_key:
        default:
          get_input: agent_key
      auth:
        default:
          customer:
            get_input: customer
          password:
            get_input: password
          url:
            get_input: service_url
          username:
            get_input: username
          verify_ca_cert: false
      cloudify_agent:
        default:
          user:
            get_input: agent_user
      network:
        default:
          get_input: network
      vdc:
        default:
          get_input: vdc
  dice.hosts.Large:
    derived_from: dice.hosts.Custom
    properties:
      disk:
        default:
          get_input: large_disk
      image:
        default:
          get_input: large_image_id
      server_type:
        default:
          get_input: large_server_type
  dice.hosts.Medium:
    derived_from: dice.hosts.Custom
    properties:
      disk:
        default:
          get_input: medium_disk
      image:
        default:
          get_input: medium_image_id
      server_type:
        default:
          get_input: medium_server_type
  dice.hosts.Small:
    derived_from: dice.hosts.Custom
    properties:
      disk:
        default:
          get_input: small_disk
      image:
        default:
          get_input: small_image_id
      server_type:
        default:
          get_input: small_server_type
  dice.hosts.Unimplemented:
    derived_from: cloudify.nodes.Root
plugins:
  dice:
    executor: host_agent
    source: https://github.com/dice-project/DICE-Deployment-Cloudify/archive/0.1.3.zip
relationships:
  dice.relationships.ContainedIn:
    derived_from: cloudify.relationships.contained_in
  dice.relationships.Needs:
    derived_from: cloudify.relationships.depends_on
  dice.relationships.ProtectedBy:
    derived_from: dice.relationships.Unimplemented
  dice.relationships.Unimplemented:
    derived_from: cloudify.relationships.depends_on
  dice.relationships.cassandra.ConnectedToSeed:
    derived_from: cloudify.relationships.connected_to
    properties:
      connection_type:
        default: all_to_one
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: dice.dice_plugin.tasks.cassandra.gather_seeds
  dice.relationships.hadoop.ConnectedToNameNode:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: dice.dice_plugin.tasks.base.copy_ip_address
          inputs:
            property:
              default: namenode_addr
  dice.relationships.hadoop.ConnectedToResourceManager:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: dice.dice_plugin.tasks.base.copy_ip_address
          inputs:
            property:
              default: resourcemanager_addr
  dice.relationships.spark.ConnectedToMaster:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: dice.dice_plugin.tasks.base.copy_ip_address
          inputs:
            property:
              default: master_ip
  dice.relationships.storm.ConnectedToNimbus:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: dice.dice_plugin.tasks.base.copy_ip_address
          inputs:
            property:
              default: storm_nimbus_ip
  dice.relationships.storm.ConnectedToZookeeperQuorum:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: dice.dice_plugin.tasks.base.copy_runtime_prop
          inputs:
            property:
              default: zookeeper_quorum
  dice.relationships.storm.SubmittedBy:
    derived_from: cloudify.relationships.contained_in
    properties:
      connection_type:
        default: all_to_one
  dice.relationships.zookeeper.MemberOfQuorum:
    derived_from: cloudify.relationships.depends_on
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: dice.dice_plugin.tasks.base.copy_runtime_prop
          inputs:
            property:
              default: zookeeper_quorum
  dice.relationships.zookeeper.QuorumContains:
    derived_from: cloudify.relationships.depends_on
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          executor: central_deployment_agent
          implementation: dice.dice_plugin.tasks.zookeeper.gather_config
          max_retries: -1
          retry_interval: 2
