includes:
  - https://raw.githubusercontent.com/dice-project/DICE-Deployment-Cloudify/tb-wip/library/openstack.yaml
  - https://raw.githubusercontent.com/dice-project/DICE-Deployment-Cloudify/tb-wip/library/library.yaml
